nginx-ingress:
  stage: dev
  environment: bla
  name: nginx-ingress
  namespace: default
  repoUrl: http://myapp.io/
  project: myapp
  prune: true
  useHelm: false
  plugin:
    name: kustomized-helm
    env:
      - name: HELM_ARGS
        value: "--set targetRevision=master -f ../values.yaml -f ./values.yaml"